-- Esquema inicial del sistema de pedidos Rizoma.

CREATE TABLE producto (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria TEXT    NOT NULL,
    marca     TEXT,
    nombre    TEXT    NOT NULL,
    notas     TEXT,
    activo    BOOLEAN NOT NULL DEFAULT TRUE,
    orden     INTEGER
);

CREATE TABLE presentacion (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto (id) ON DELETE CASCADE,
    etiqueta    TEXT,
    precio      NUMERIC(12, 2),
    activo      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_presentacion_producto ON presentacion (producto_id);
CREATE INDEX idx_producto_categoria ON producto (categoria);

CREATE TABLE cliente (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    TEXT NOT NULL,
    apellido  TEXT NOT NULL,
    direccion TEXT NOT NULL,
    celular   TEXT NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cliente_celular ON cliente (celular);

CREATE TABLE pedido (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT NOT NULL REFERENCES cliente (id),
    dia_entrega TEXT,
    total       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estado      TEXT NOT NULL DEFAULT 'NUEVO',
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE pedido_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT NOT NULL REFERENCES pedido (id) ON DELETE CASCADE,
    presentacion_id BIGINT REFERENCES presentacion (id),
    nombre_producto TEXT NOT NULL,
    etiqueta        TEXT,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    cantidad        INTEGER NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL
);

CREATE INDEX idx_pedido_item_pedido ON pedido_item (pedido_id);
