-- Convierte la categoría (texto libre en producto) en una entidad propia.

CREATE TABLE categoria (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT    NOT NULL UNIQUE,
    orden  INTEGER,
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

-- 1) Poblar con las categorías existentes; orden inicial según primera aparición.
INSERT INTO categoria (nombre, orden)
SELECT categoria, MIN(orden)
FROM producto
GROUP BY categoria;

-- 2) Normalizar el orden a una secuencia 1..N (por aparición, luego alfabético).
WITH ordenadas AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY orden NULLS LAST, nombre) AS rn
    FROM categoria
)
UPDATE categoria c
SET orden = o.rn
FROM ordenadas o
WHERE c.id = o.id;

-- 3) Agregar la FK en producto y backfillear por nombre.
ALTER TABLE producto ADD COLUMN categoria_id BIGINT REFERENCES categoria (id);

UPDATE producto p
SET categoria_id = c.id
FROM categoria c
WHERE c.nombre = p.categoria;

-- 4) Cerrar: la FK pasa a obligatoria y se elimina la columna de texto.
ALTER TABLE producto ALTER COLUMN categoria_id SET NOT NULL;
ALTER TABLE producto DROP COLUMN categoria;

CREATE INDEX idx_producto_categoria_id ON producto (categoria_id);
